name: Delete Neon Branch 
run-name: Delete Neon Branch ${{ github.head_ref || github.ref_name }}
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  delete-neon-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch: ${{ github.head_ref || github.ref_name }}
          api_key: ${{ secrets.NEON_API_KEY }}
          
      - name: Deleted neon db branch
        run: echo Deleting database branch ${{ github.head_ref || github.ref_name }} from neon console.
    
