name: Create Neon Branch with GitHub Actions Demo
run-name: Create a Neon Branch 🚀
on:
  pull_request:
    branches: [ main ]
jobs:
  Create-Neon-Branch:
    runs-on: ubuntu-latest
    steps:
      - uses: neondatabase/create-branch-action@v5.0.0
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          parent_id: ${{ secrets.NEON_PARENT_BRANCH_ID }}
          branch_name: ${{ github.ref_name }}
          api_key: ${{ secrets.NEON_API_KEY }}
