name: Create Neon Branch with GitHub Actions Demo
run-name: Create a Neon Branch 🚀
on:
  pull_request:
    branches: [ main ]
jobs:
  create_preview_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: neondatabase/create-branch-action@v5.0.0
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          parent: ${{ secrets.NEON_PARENT_BRANCH_ID }}
          branch_name: ${{ github.head_ref || github.ref_name }}
          database: uturn_dev
          username: api_user
          api_key: ${{ secrets.NEON_API_KEY }}
        id: create-branch
      - name: Branch name
        run: echo running on branch ${{ github.head_ref || github.ref_name }}
      - name: Check output
        run: echo hostname with pooler ${{ steps.create-branch.outputs.host_with_pooler }} and ${{ steps.create-branch.outputs.password }}
      
    outputs:
      db_url: ${{ steps.create-branch.outputs.db_url }}
      db_url_with_pooler: ${{ steps.create-branch.outputs.db_url_with_pooler }}
      host: ${{ steps.create-branch.outputs.host }}
      host_with_pooler: ${{ steps.create-branch.outputs.host_with_pooler }}
      branch_id: ${{ steps.create-branch.outputs.branch_id }}
      password: ${{ steps.create-branch.outputs.password }}
      database_name: uturn_dev

  Execute-seed-data:
    runs-on: ubuntu-latest
    needs: create_preview_branch

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Inserting seed data
        run: psql 'postgresql://api_user:${{ needs.create_preview_branch.outputs.password }}@${{ needs.create_preview_branch.outputs.host_with_pooler }}/${{ needs.create_preview_branch.outputs.database_name }}?sslmode=require' -f seed.sql
