name: Create Neon Branch with GitHub Actions Demo
run-name: Create a Neon Branch 🚀
on:
  pull_request:
    branches: [ main ]
jobs:
  Execute-seed-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check working directory
        run: cd .github/workflows
      - name: List files in directory
        run: ls -l
      - name: Insert seed data
        run: psql -d postgresql://api_user@${{needs.create-branch.outputs.host_with_pooler}}/${{ github.head_ref || github.ref_name }} -f seed.sql
        
