name: Create Neon Branch with GitHub Actions Demo
run-name: Create a Neon Branch 🚀
on:
  pull_request:
    branches: [ main ]
jobs:
  Execute-seed-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check working directory
        run: cd .github/workflows  # Print current working directory

      - name: List files in directory
        run: ls -l
        
      - name: Inserting seed data
        run: psql 'postgresql://api_user:GAfMRQJwL7S2@ep-shrill-dust-a2v5t7y2-pooler.eu-central-1.aws.neon.tech/uturn_dev?sslmode=require' -f ../../seed.sql
        
