name: Create Neon Branch with GitHub Actions Demo
run-name: Create a Neon Branch 🚀
on:
  push:
    branches: [ main ]
jobs:
  create_preview_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: neondatabase/create-branch-action@v5.0.0
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          parent: ${{ secrets.NEON_PARENT_BRANCH_ID }}
          branch_name: demo
          database: uturn_dev
          username: api_user
          api_key: ${{ secrets.NEON_API_KEY }}
        id: create-branch
      - name: Branch name
        run: echo running on branch ${{ github.head_ref || github.ref_name }}
      - name: Check outoput
        run: echo hostname with pooler ${{ steps.create-branch.outputs.host_with_pooler }} and ${{ steps.create-branch.outputs.password }}
      
    outputs:
      db_url: ${{ steps.create-branch.outputs.db_url }}
      db_url_with_pooler: ${{ steps.create-branch.outputs.db_url_with_pooler }}
      host: ${{ steps.create-branch.outputs.host }}
      host_with_pooler: ${{ steps.create-branch.outputs.host_with_pooler }}
      branch_id: ${{ steps.create-branch.outputs.branch_id }}
      password: ${{ steps.create-branch.outputs.password }}
      database_name: ${{ github.head_ref || github.ref_name }}

  Execute-seed-data:
    runs-on: ubuntu-latest
    needs: create_preview_branch

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check working directory
        run: pwd  # Print current working directory

      - name: List files in directory
        run: ls -l

      - name: Get host_with_pooler from create_preview_branch job
        run: echo "Host with pooler: ${{ needs.create_preview_branch.outputs.host_with_pooler }}"
        
      - name: Display info
        run: echo postgresql://api_user:${{ needs.create-branch.outputs.password }}@${{ needs.create-branch.outputs.host_with_pooler}}/${{ needs.create-branch.outputs.database_name}}?sslmode=require
