name: Create Neon Branch with GitHub Actions Demo
run-name: Create a Neon Branch 🚀
on:
  pull_request:
    branches: [ main ]
jobs:
  Create-Neon-Branch:
    runs-on: ubuntu-latest
    steps:
      - uses: neondatabase/create-branch-action@v5.0.0
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          parent: ${{ secrets.NEON_PARENT_BRANCH_ID }}
          branch_name: ${{ github.head_ref || github.ref_name }}
          database: uturn_dev
          username: api_user
          api_key: ${{ secrets.NEON_API_KEY }}
        id: create-branch  
      - name: Branch name
        run: echo running on branch ${{ github.head_ref || github.ref_name }}

outputs:
  db_url:
    description: 'New branch DATABASE_URL'
    value: ${{ steps.create-branch.outputs.db_url }}
  db_url_with_pooler:
    description: 'New branch DATABASE_URL with pooling enabled'
    value: ${{ steps.create-branch.outputs.db_url_with_pooler }}
  host:
    description: 'New branch host'
    value: ${{ steps.create-branch.outputs.host }}
  host_with_pooler:
    description: 'New branch host with pooling enabled'
    value: ${{ steps.create-branch.outputs.host_with_pooler }}
  branch_id:
    description: 'New branch id'
    value: ${{ steps.create-branch.outputs.branch_id }}
  password:
    description: 'Password for connecting to the new branch database with the input username'
    value: ${{ steps.create-branch.outputs.password }}      
